./lem-in < maps/error/comment_in_link
./lem-in < maps/error/comment_in_room
./lem-in < maps/error/empty_file
./lem-in < maps/error/empty_line_after_ants
./lem-in < maps/error/empty_line_between_rooms_and_links
./lem-in < maps/error/empty_line_in_links
./lem-in < maps/error/empty_line_in_rooms
./lem-in < maps/error/end_after_end
./lem-in < maps/error/end_after_start
./lem-in < maps/error/invalid_ants
./lem-in < maps/error/invalid_room_coordinate
./lem-in < maps/error/invalid_room_in_link_0
./lem-in < maps/error/invalid_room_in_link_1
./lem-in < maps/error/invalid_room_in_link_2
./lem-in < maps/error/invalid_room_name_0
./lem-in < maps/error/link_after_end
./lem-in < maps/error/link_after_start
./lem-in < maps/error/link_among_rooms
./lem-in < maps/error/missing_room_coordinate
./lem-in < maps/error/my_test1
./lem-in < maps/error/negative_ants
./lem-in < maps/error/no_ants
./lem-in < maps/error/no_end
./lem-in < maps/error/no_links
./lem-in < maps/error/no_path_from_start_to_end
./lem-in < maps/error/no_rooms
./lem-in < maps/error/no_start
./lem-in < maps/error/room_among_links
./lem-in < maps/error/same_room_twice
./lem-in < maps/error/start_after_end
./lem-in < maps/error/start_after_start
./lem-in < maps/error/two_ends
./lem-in < maps/error/two_starts
